const ACT_CATS=['Work','Learning','Exercise','Personal','Health','Social','Creative','Other'];
const EXP_CATS=['Food','Transport','Bills','Shopping','Health','Entertainment','Stock','Aura Silver','Petrol','Parking','Other'];
const COLORS={Work:'#2563eb',Learning:'#7c3aed',Exercise:'#059669',Personal:'#d97706',Health:'#dc2626',Social:'#db2777',Creative:'#0891b2',Other:'#64748b',Food:'#ea580c',Transport:'#2563eb',Bills:'#7c3aed',Shopping:'#db2777',Entertainment:'#059669',Stock:'#16a34a','Aura Silver':'#64748b',Petrol:'#dc2626',Parking:'#ca8a04'};
const state={acts:[],exps:[],view:'dashboard',dashPeriod:'today',analyticsPeriod:'month',editId:null,editType:null,charts:{},loaded:false};
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10),nowTime=()=>new Date().toTimeString().slice(0,5),money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const fmtDate=s=>s?new Date(s+'T00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'',shortDate=s=>s?new Date(s+'T00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'';
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function setDefaults(){$('aDate').value=today();$('eDate').value=today();$('aTime').value=nowTime()}
function daysAgo(n){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)}
function periodDates(p){if(p==='today')return[today(),today()];if(p==='week')return[daysAgo(6),today()];if(p==='month'){const d=new Date();d.setDate(1);return[d.toISOString().slice(0,10),today()]}return['0000-01-01',today()]}
function inPeriod(date,p){const[a,b]=periodDates(p);return date>=a&&date<=b} function sortNewest(a,b){return String(b.date||'').localeCompare(String(a.date||''))||String(b.time||'').localeCompare(String(a.time||''))}
function allEntries(){return[...state.acts.map(x=>({...x,type:'activity'})),...state.exps.map(x=>({...x,type:'expense'}))].sort(sortNewest)}
function activeDays(){return new Set(state.acts.filter(a=>a.date).map(a=>a.date))}
function streak(){let d=new Date();d.setHours(0,0,0,0);let key=d.toISOString().slice(0,10),days=activeDays(),n=0;while(days.has(key)){n++;d.setDate(d.getDate()-1);key=d.toISOString().slice(0,10)}return n}
function renderChips(containerId,hiddenId,cats){const w=$(containerId),h=$(hiddenId);w.innerHTML=cats.map(c=>`<button type="button" class="chip ${h.value===c?'active':''}" data-chip="${esc(c)}">${esc(c)}</button>`).join('');w.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{h.value=b.dataset.chip;renderChips(containerId,hiddenId,cats)})}
function populateFilters(){$('activityFilter').innerHTML='<option value="">All categories</option>'+ACT_CATS.map(c=>`<option>${esc(c)}</option>`).join('');$('expenseFilter').innerHTML='<option value="">All categories</option>'+EXP_CATS.map(c=>`<option>${esc(c)}</option>`).join('')}
function statusClass(s){return s==='Completed'?'done':s==='Pending'?'pending':s==='In Progress'?'progress':'cancelled'} function empty(msg){return`<div class="empty-state"><div class="empty-icon">✦</div><p>${esc(msg)}</p></div>`}
function activityEntry(a){const col=COLORS[a.category]||COLORS.Other;return`<div class="entry"><i class="entry-dot" style="background:${col}"></i><div class="entry-main"><div class="entry-title">${esc(a.name)}</div><div class="entry-meta">${esc(a.category)} · ${shortDate(a.date)} ${esc(a.time||'')} ${a.notes?'· '+esc(String(a.notes).slice(0,42)):''}</div><span class="badge ${statusClass(a.status)}">${esc(a.status||'')}</span></div><div class="entry-value">${a.duration?Number(a.duration).toFixed(2).replace(/\.00$/,'')+'h':''}</div><div class="entry-actions"><button class="mini-action" data-edit="activity:${esc(a.id)}">✎</button><button class="mini-action delete" data-delete="activity:${esc(a.id)}">×</button></div></div>`}
function expenseEntry(e){const col=COLORS[e.category]||COLORS.Other;return`<div class="entry"><i class="entry-dot" style="background:${col}"></i><div class="entry-main"><div class="entry-title">${esc(e.name)}</div><div class="entry-meta">${esc(e.category)} · ${esc(e.mode||'')} · ${shortDate(e.date)} ${e.notes?'· '+esc(String(e.notes).slice(0,42)):''}</div></div><div class="entry-value">${money(e.amount)}</div><div class="entry-actions"><button class="mini-action" data-edit="expense:${esc(e.id)}">✎</button><button class="mini-action delete" data-delete="expense:${esc(e.id)}">×</button></div></div>`}
function renderDashboard(){const p=state.dashPeriod,acts=state.acts.filter(a=>inPeriod(a.date||'',p)),exps=state.exps.filter(e=>inPeriod(e.date||'',p)),done=acts.filter(a=>a.status==='Completed').length,hours=acts.reduce((s,a)=>s+Number(a.duration||0),0),spent=exps.reduce((s,e)=>s+Number(e.amount||0),0),rate=acts.length?Math.round(done/acts.length*100):0,[start,end]=periodDates(p);$('todayLabel').textContent=p==='today'?'TODAY':p==='week'?'LAST 7 DAYS':p==='month'?'THIS MONTH':'ALL TIME';$('daySubtitle').textContent=p==='today'?'Your activity and spending at a glance.':`${fmtDate(start)} – ${fmtDate(end)}`;$('kpiActivities').textContent=acts.length;$('kpiActivityMeta').textContent=`${done} completed`;$('kpiHours').textContent=hours.toFixed(1).replace(/\.0$/,'')+'h';$('kpiHoursMeta').textContent=acts.length?'Across activities':'No time logged';$('kpiSpent').textContent=money(spent);$('kpiSpentMeta').textContent=p==='today'?'Today':p==='week'?'Last 7 days':p==='month'?'This month':'All time';$('kpiStreak').textContent=streak()+' day'+(streak()===1?'':'s');$('completionNumber').textContent=rate+'%';$('completionBar').style.width=rate+'%';$('completionText').textContent=acts.length?`${done} of ${acts.length} completed`:'No activities yet';$('completionHours').textContent=hours.toFixed(1).replace(/\.0$/,'')+'h logged';$('recentActivities').innerHTML=state.acts.length?[...state.acts].sort(sortNewest).slice(0,5).map(activityEntry).join(''):empty('No activities yet.');$('recentExpenses').innerHTML=state.exps.length?[...state.exps].sort(sortNewest).slice(0,5).map(expenseEntry).join(''):empty('No expenses yet.');renderDonut(exps);renderLine()}
function destroyChart(k){if(state.charts[k]){state.charts[k].destroy();delete state.charts[k]}}
function renderDonut(exps){const totals={};exps.forEach(e=>totals[e.category]=(totals[e.category]||0)+Number(e.amount||0));const rows=Object.entries(totals).sort((a,b)=>b[1]-a[1]);destroyChart('expenseDonut');$('expenseLegend').innerHTML=rows.slice(0,6).map(([c,v])=>`<span class="legend-item"><i class="legend-dot" style="background:${COLORS[c]||COLORS.Other}"></i>${esc(c)} ${money(v)}</span>`).join('');if(!rows.length)return;state.charts.expenseDonut=new Chart($('expenseDonut'),{type:'doughnut',data:{labels:rows.map(x=>x[0]),datasets:[{data:rows.map(x=>x[1]),backgroundColor:rows.map(x=>COLORS[x[0]]||COLORS.Other),borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{display:false}}}})}
function renderLine(){const labels=[],values=[];for(let i=6;i>=0;i--){const d=daysAgo(i);labels.push(new Date(d+'T00:00').toLocaleDateString('en-IN',{weekday:'short'}));values.push(state.exps.filter(e=>e.date===d).reduce((s,e)=>s+Number(e.amount||0),0))}destroyChart('spendingLine');state.charts.spendingLine=new Chart($('spendingLine'),{type:'line',data:{labels,datasets:[{data:values,borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.09)',fill:true,tension:.35,pointRadius:3,pointBackgroundColor:'#2563eb'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:10},color:'#94a3b8'}},y:{beginAtZero:true,grid:{color:'rgba(148,163,184,.12)'},ticks:{font:{size:10},color:'#94a3b8',callback:v=>'₹'+v}}}}})}
function renderActivities(){const q=($('activitySearch').value||'').toLowerCase(),cat=$('activityFilter').value,rows=state.acts.filter(a=>(!cat||a.category===cat)&&(!q||`${a.name} ${a.category} ${a.notes||''}`.toLowerCase().includes(q))).sort(sortNewest);$('activityCount').textContent=`${rows.length} entr${rows.length===1?'y':'ies'}`;$('activityList').innerHTML=rows.length?rows.map(activityEntry).join(''):empty('No matching activities.')}
function renderExpenses(){const q=($('expenseSearch').value||'').toLowerCase(),cat=$('expenseFilter').value,rows=state.exps.filter(e=>(!cat||e.category===cat)&&(!q||`${e.name} ${e.category} ${e.mode||''} ${e.notes||''}`.toLowerCase().includes(q))).sort(sortNewest);$('expenseCount').textContent=`${rows.length} entr${rows.length===1?'y':'ies'}`;$('expenseList').innerHTML=rows.length?rows.map(expenseEntry).join(''):empty('No matching expenses.')}
function renderAnalytics(){const p=state.analyticsPeriod,acts=state.acts.filter(a=>inPeriod(a.date||'',p)),exps=state.exps.filter(e=>inPeriod(e.date||'',p)),topA={},topE={};acts.forEach(a=>topA[a.category]=(topA[a.category]||0)+Number(a.duration||0));exps.forEach(e=>topE[e.category]=(topE[e.category]||0)+Number(e.amount||0));const ta=Object.entries(topA).sort((a,b)=>b[1]-a[1])[0],te=Object.entries(topE).sort((a,b)=>b[1]-a[1])[0];$('topActivity').textContent=ta?ta[0]:'—';$('topActivityMeta').textContent=ta?ta[1].toFixed(1).replace(/\.0$/,'')+'h logged':'No data';$('topExpense').textContent=te?te[0]:'—';$('topExpenseMeta').textContent=te?money(te[1]):'No data';const uniqueDays=new Set(exps.map(e=>e.date)).size,total=exps.reduce((s,e)=>s+Number(e.amount||0),0);$('avgSpend').textContent=money(uniqueDays?total/uniqueDays:0);$('avgSpendMeta').textContent=uniqueDays?`${uniqueDays} spending days`:'No spending data';destroyChart('activityBar');const ar=Object.entries(topA).sort((a,b)=>b[1]-a[1]);state.charts.activityBar=new Chart($('activityBar'),{type:'bar',data:{labels:ar.map(x=>x[0]),datasets:[{data:ar.map(x=>x[1]),backgroundColor:ar.map(x=>COLORS[x[0]]||COLORS.Other),borderRadius:7,borderSkipped:false}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:9},color:'#94a3b8'}},y:{beginAtZero:true,grid:{color:'rgba(148,163,184,.12)'},ticks:{font:{size:9},color:'#94a3b8'}}}}});const modes={};exps.forEach(e=>modes[e.mode||'Other']=(modes[e.mode||'Other']||0)+Number(e.amount||0));const mr=Object.entries(modes);destroyChart('paymentPie');$('paymentLegend').innerHTML=mr.map(([c,v])=>`<span class="legend-item"><i class="legend-dot" style="background:${COLORS[c]||'#64748b'}"></i>${esc(c)} ${money(v)}</span>`).join('');if(mr.length)state.charts.paymentPie=new Chart($('paymentPie'),{type:'pie',data:{labels:mr.map(x=>x[0]),datasets:[{data:mr.map(x=>x[1]),backgroundColor:['#2563eb','#059669','#ea580c','#7c3aed','#64748b'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});const max=te?te[1]:1;$('categoryBars').innerHTML=Object.entries(topE).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="category-row"><span>${esc(c)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,v/max*100)}%;background:${COLORS[c]||COLORS.Other}"></div></div><b>${money(v)}</b></div>`).join('')||empty('No expense data for this period.')}
function renderHistory(){const q=($('historySearch').value||'').toLowerCase(),type=$('historyType').value,rows=allEntries().filter(e=>(type==='all'||e.type===type)&&(!q||`${e.name} ${e.category} ${e.notes||''} ${e.mode||''}`.toLowerCase().includes(q)));$('historyList').innerHTML=rows.length?rows.map(e=>`<div class="timeline-entry ${e.type}"><div class="timeline-date">${shortDate(e.date)}<br>${esc(e.time||'')}</div><i class="timeline-line"></i><div><div class="timeline-title">${esc(e.name)}</div><div class="timeline-meta">${esc(e.category)}${e.type==='activity'?' · '+esc(e.status||'')+' · '+Number(e.duration||0).toFixed(2).replace(/\.00$/,'')+'h':' · '+esc(e.mode||'')}</div></div><div class="timeline-amount">${e.type==='expense'?money(e.amount):''}</div></div>`).join(''):empty('No history matches your search.')}
function renderAll(){if(!state.loaded)return;renderDashboard();renderActivities();renderExpenses();renderAnalytics();renderHistory()}
function navigate(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:['OVERVIEW','Good day 👋'],activities:['TRACK','Activities'],expenses:['MONEY','Expenses'],analytics:['INSIGHTS','Analytics'],history:['TIMELINE','History'],settings:['CONTROL CENTER','Settings']};$('viewKicker').textContent=titles[view][0];$('viewTitle').textContent=titles[view][1];$('sidebar').classList.remove('open');$('sidebarOverlay').classList.remove('open');if(view==='analytics')setTimeout(renderAnalytics,30)}
function openEdit(type,id){const item=type==='activity'?state.acts.find(x=>x.id===id):state.exps.find(x=>x.id===id);if(!item)return;state.editId=id;state.editType=type;$('modalKicker').textContent='EDIT '+type.toUpperCase();$('modalTitle').textContent=type==='activity'?'Edit activity':'Edit expense';const cats=type==='activity'?ACT_CATS:EXP_CATS,cat=item.category||cats[0];$('editForm').innerHTML=type==='activity'?`<label>Name<input id="mName" required value="${esc(item.name)}"></label><label>Category<select id="mCategory">${cats.map(c=>`<option ${c===cat?'selected':''}>${esc(c)}</option>`).join('')}</select></label><div class="form-row"><label>Date<input id="mDate" type="date" required value="${esc(item.date||today())"></label><label>Time<input id="mTime" type="time" value="${esc(item.time||'')}"></label></div><div class="form-row"><label>Duration<input id="mDuration" type="number" min="0" step="0.25" value="${Number(item.duration||0)}"></label><label>Status<select id="mStatus">${['Completed','Pending','In Progress','Cancelled'].map(s=>`<option ${s===item.status?'selected':''}>${s}</option>`).join('')}</select></label></div><label>Notes<textarea id="mNotes" rows="3">${esc(item.notes||'')}</textarea><div class="form-actions"><button type="button" class="secondary-btn" id="modalCancel">Cancel</button><button class="primary-btn" type="submit">Save changes</button></div>`:`<label>Name<input id="mName" required value="${esc(item.name)}"></label><label>Category<select id="mCategory">${cats.map(c=>`<option ${c===cat?'selected':''}>${esc(c)}</option>`).join('')}</select></label><div class="form-row"><label>Amount (₹)<input id="mAmount" type="number" min="0.01" step="0.01" required value="${Number(item.amount||0)}"></label><label>Payment mode<select id="mMode">${['UPI','Cash','Card','Net Banking','Other'].map(s=>`<option ${s===item.mode?'selected':''}>${s}</option>`).join('')}</select></label></div><label>Date<input id="mDate" type="date" required value="${esc(item.date||today())}"></label><label>Notes<textarea id="mNotes" rows="3">${esc(item.notes||'')}</textarea><div class="form-actions"><button type="button" class="secondary-btn" id="modalCancel">Cancel</button><button class="primary-btn" type="submit">Save changes</button></div>`;$('modalBackdrop').classList.add('open');$('modalCancel').onclick=closeModal}
function closeModal(){$('modalBackdrop').classList.remove('open');state.editId=null;state.editType=null}
async function deleteEntry(type,id){if(!confirm(`Delete this ${type==='activity'?'activity':'expense'}? This cannot be undone.`))return;try{await deleteDoc(doc(db,type==='activity'?'activities':'expenses',id));toast('Deleted successfully')}catch(e){console.error(e);toast('Could not delete entry')}}
function csv(rows,headers){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;return[headers.map(q).join(','),...rows.map(r=>headers.map(h=>q(r[h])).join(','))].join('\n')}
function download(name,text,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove()}
function exportActs(){download(`daily-tracker-activities-${today()}.csv`,csv(state.acts,['date','time','name','category','duration','status','notes']));toast('Activities exported')}
function exportExps(){download(`daily-tracker-expenses-${today()}.csv`,csv(state.exps,['date','name','category','amount','mode','notes']));toast('Expenses exported')}
function exportBackup(){download(`daily-tracker-backup-${today()}.json`,JSON.stringify({exportedAt:new Date().toISOString(),activities:state.acts,expenses:state.exps},null,2),'application/json');toast('Backup exported')}
async function clearAll(){if(!state.acts.length&&!state.exps.length){toast('There is no data to delete');return}if(!confirm('Delete ALL activities and expenses? This cannot be undone. Export a backup first if needed.'))return;try{await Promise.all([...state.acts.map(a=>deleteDoc(doc(db,'activities',a.id))),...state.exps.map(e=>deleteDoc(doc(db,'expenses',e.id)))]);toast('All tracker data deleted')}catch(e){console.error(e);toast('Some data could not be deleted')}}
async function saveActivity(e){e.preventDefault();const name=$('aName').value.trim();if(!name)return;try{await addDoc(collection(db,'activities'),{name,category:$('aCategory').value,date:$('aDate').value||today(),time:$('aTime').value||nowTime(),duration:Number($('aDuration').value||0),status:$('aStatus').value,notes:$('aNotes').value.trim()});e.target.reset();$('aCategory').value='Work';setDefaults();renderChips('activityCats','aCategory',ACT_CATS);toast('Activity saved ✓')}catch(err){console.error(err);toast('Could not save activity')}}
async function saveExpense(e){e.preventDefault();const name=$('eName').value.trim(),amount=Number($('eAmount').value);if(!name||!amount||amount<=0){toast('Enter a valid name and amount');return}try{await addDoc(collection(db,'expenses'),{name,category:$('eCategory').value,date:$('eDate').value||today(),amount,mode:$('eMode').value,notes:$('eNotes').value.trim()});e.target.reset();$('eCategory').value='Food';setDefaults();renderChips('expenseCats','eCategory',EXP_CATS);toast('Expense saved ✓')}catch(err){console.error(err);toast('Could not save expense')}}
async function saveEdit(e){e.preventDefault();if(!state.editId||!state.editType)return;const data=state.editType==='activity'?{name:$('mName').value.trim(),category:$('mCategory').value,date:$('mDate').value,time:$('mTime').value,duration:Number($('mDuration').value||0),status:$('mStatus').value,notes:$('mNotes').value.trim()}:{name:$('mName').value.trim(),category:$('mCategory').value,amount:Number($('mAmount').value),mode:$('mMode').value,date:$('mDate').value,notes:$('mNotes').value.trim()};try{await updateDoc(doc(db,state.editType==='activity'?'activities':'expenses',state.editId),data);closeModal();toast('Changes saved ✓')}catch(err){console.error(err);toast('Could not save changes')}}
function themeInit(){const dark=localStorage.getItem('mdt_theme')==='dark';document.body.classList.toggle('dark',dark);$('darkSwitch').classList.toggle('on',dark)}function toggleTheme(){const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);$('darkSwitch').classList.toggle('on',dark);localStorage.setItem('mdt_theme',dark?'dark':'light')}
function openNew(type){navigate(type==='activity'?'activities':'expenses');setTimeout(()=>$(type==='activity'?'aName':'eName').focus(),80)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));document.querySelectorAll('[data-open-modal]').forEach(b=>b.addEventListener('click',()=>openNew(b.dataset.openModal)));$('mobileMenu').onclick=()=>{$('sidebar').classList.add('open');$('sidebarOverlay').classList.add('open')};$('sidebarOverlay').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarOverlay').classList.remove('open')};$('quickAddBtn').onclick=()=>openNew('activity');document.querySelectorAll('[data-period]').forEach(b=>b.addEventListener('click',()=>{const p=b.closest('.period-tabs');p.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(p.id==='dashPeriod'){state.dashPeriod=b.dataset.period;renderDashboard()}else{state.analyticsPeriod=b.dataset.period;renderAnalytics()}}));$('activityForm').onsubmit=saveActivity;$('expenseForm').onsubmit=saveExpense;$('editForm').onsubmit=saveEdit;$('modalClose').onclick=closeModal;$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))closeModal()};$('themeBtn').onclick=toggleTheme;$('darkSwitch').onclick=toggleTheme;$('activitySearch').oninput=renderActivities;$('activityFilter').onchange=renderActivities;$('expenseSearch').oninput=renderExpenses;$('expenseFilter').onchange=renderExpenses;$('historySearch').oninput=renderHistory;$('historyType').onchange=renderHistory;$('exportActivities').onclick=exportActs;$('exportExpenses').onclick=exportExps;$('exportBackup').onclick=exportBackup;$('clearData').onclick=clearAll;document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const [type,id]=edit.dataset.edit.split(':');openEdit(type,id)}if(del){const [type,id]=del.dataset.delete.split(':');deleteEntry(type,id)}})}
function clock(){$('liveTime').textContent=new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true})}
function loadData(){if(!window.db||!window.onSnapshot){toast('Firebase is not ready');return}window.onSnapshot(collection(db,'activities'),snap=>{state.acts=snap.docs.map(d=>({id:d.id,...d.data()}));state.loaded=true;renderAll()},err=>{console.error(err);toast('Unable to load activities')});window.onSnapshot(collection(db,'expenses'),snap=>{state.exps=snap.docs.map(d=>({id:d.id,...d.data()}));state.loaded=true;renderAll()},err=>{console.error(err);toast('Unable to load expenses')})}
function init(){bind();themeInit();populateFilters();renderChips('activityCats','aCategory',ACT_CATS);renderChips('expenseCats','eCategory',EXP_CATS);setDefaults();clock();setInterval(clock,1000);loadData()}
window.addEventListener('DOMContentLoaded',init);