const ACT_CATS=['Work','Learning','Exercise','Personal','Health','Social','Creative','Other'];
const EXP_CATS=['Food','Transport','Bills','Shopping','Health','Entertainment','Stock','Aura Silver','Petrol','Parking','Other'];
const COLORS={Work:'#2563eb',Learning:'#7c3aed',Exercise:'#059669',Personal:'#d97706',Health:'#dc2626',Social:'#db2777',Creative:'#0891b2',Other:'#64748b',Food:'#ea580c',Transport:'#2563eb',Bills:'#7c3aed',Shopping:'#db2777',Entertainment:'#059669',Stock:'#16a34a','Aura Silver':'#64748b',Petrol:'#dc2626',Parking:'#ca8a04'};
const S={acts:[],exps:[],loaded:false,view:'dashboard',dash:'today',analytics:'month',charts:{},edit:null};
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10), now=()=>new Date().toTimeString().slice(0,5), money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const dateText=s=>s?new Date(s+'T00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'', shortDate=s=>s?new Date(s+'T00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'';
const ago=n=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d.toISOString().slice(0,10)};
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function range(p){if(p==='today')return[today(),today()];if(p==='week')return[ago(6),today()];if(p==='month'){const d=new Date();d.setDate(1);return[d.toISOString().slice(0,10),today()]}return['0000-01-01',today()]}
function inRange(d,p){const[r1,r2]=range(p);return d>=r1&&d<=r2} function newest(a,b){return String(b.date||'').localeCompare(String(a.date||''))||String(b.time||'').localeCompare(String(a.time||''))}
function all(){return[...S.acts.map(x=>({...x,type:'activity'})),...S.exps.map(x=>({...x,type:'expense'}))].sort(newest)}
function streak(){const days=new Set(S.acts.map(a=>a.date));let d=new Date();d.setHours(0,0,0,0);let k=d.toISOString().slice(0,10),n=0;while(days.has(k)){n++;d.setDate(d.getDate()-1);k=d.toISOString().slice(0,10)}return n}
function chips(wid,hid,cats){const w=$(wid),h=$(hid);w.innerHTML=cats.map(c=>`<button type="button" class="chip ${h.value===c?'active':''}" data-chip="${esc(c)}">${esc(c)}</button>`).join('');w.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{h.value=b.dataset.chip;chips(wid,hid,cats)})}
function empty(m){return`<div class="empty-state"><div class="empty-icon">✦</div><p>${esc(m)}</p></div>`}
function statusClass(s){return s==='Completed'?'done':s==='Pending'?'pending':s==='In Progress'?'progress':'cancelled'}
function actHTML(a){return`<div class="entry"><i class="entry-dot" style="background:${COLORS[a.category]||COLORS.Other}"></i><div class="entry-main"><div class="entry-title">${esc(a.name)}</div><div class="entry-meta">${esc(a.category)} · ${shortDate(a.date)} ${esc(a.time||'')}</div><span class="badge ${statusClass(a.status)}">${esc(a.status||'')}</span></div><div class="entry-value">${a.duration?Number(a.duration).toFixed(2).replace(/\.00$/,'')+'h':''}</div><div class="entry-actions"><button class="mini-action" data-edit="activity:${esc(a.id)}">✎</button><button class="mini-action delete" data-delete="activity:${esc(a.id)}">×</button></div></div>`}
function expHTML(e){return`<div class="entry"><i class="entry-dot" style="background:${COLORS[e.category]||COLORS.Other}"></i><div class="entry-main"><div class="entry-title">${esc(e.name)}</div><div class="entry-meta">${esc(e.category)} · ${esc(e.mode||'')} · ${shortDate(e.date)}</div></div><div class="entry-value">${money(e.amount)}</div><div class="entry-actions"><button class="mini-action" data-edit="expense:${esc(e.id)}">✎</button><button class="mini-action delete" data-delete="expense:${esc(e.id)}">×</button></div></div>`}
function destroy(k){if(S.charts[k]){S.charts[k].destroy();delete S.charts[k]}}
function dashboard(){const p=S.dash,A=S.acts.filter(a=>inRange(a.date||'',p)),E=S.exps.filter(e=>inRange(e.date||'',p)),done=A.filter(a=>a.status==='Completed').length,h=A.reduce((s,a)=>s+Number(a.duration||0),0),sp=E.reduce((s,e)=>s+Number(e.amount||0),0),rate=A.length?Math.round(done/A.length*100):0,[r1,r2]=range(p);$('todayLabel').textContent=p==='today'?'TODAY':p==='week'?'LAST 7 DAYS':p==='month'?'THIS MONTH':'ALL TIME';$('daySubtitle').textContent=p==='today'?'Your activity and spending at a glance.':`${dateText(r1)} – ${dateText(r2)}`;$('kpiActivities').textContent=A.length;$('kpiActivityMeta').textContent=`${done} completed`;$('kpiHours').textContent=h.toFixed(1).replace(/\.0$/,'')+'h';$('kpiHoursMeta').textContent=A.length?'Across activities':'No time logged';$('kpiSpent').textContent=money(sp);$('kpiSpentMeta').textContent=p==='today'?'Today':p==='week'?'Last 7 days':p==='month'?'This month':'All time';$('kpiStreak').textContent=streak()+' day'+(streak()===1?'':'s');$('completionNumber').textContent=rate+'%';$('completionBar').style.width=rate+'%';$('completionText').textContent=A.length?`${done} of ${A.length} completed`:'No activities yet';$('completionHours').textContent=h.toFixed(1).replace(/\.0$/,'')+'h logged';const ra=[...S.acts].sort(newest).slice(0,5),re=[...S.exps].sort(newest).slice(0,5);$('recentActivities').innerHTML=ra.length?ra.map(actHTML).join(''):empty('No activities yet.');$('recentExpenses').innerHTML=re.length?re.map(expHTML).join(''):empty('No expenses yet.');donut(E);line()}
function donut(E){const t={};E.forEach(e=>t[e.category]=(t[e.category]||0)+Number(e.amount||0));const r=Object.entries(t).sort((a,b)=>b[1]-a[1]);destroy('expenseDonut');$('expenseLegend').innerHTML=r.slice(0,6).map(([c,v])=>`<span class="legend-item"><i class="legend-dot" style="background:${COLORS[c]||COLORS.Other}"></i>${esc(c)} ${money(v)}</span>`).join('');if(!r.length)return;S.charts.expenseDonut=new Chart($('expenseDonut'),{type:'doughnut',data:{labels:r.map(x=>x[0]),datasets:[{data:r.map(x=>x[1]),backgroundColor:r.map(x=>COLORS[x[0]]||COLORS.Other),borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{display:false}}}})}
function line(){const labels=[],v=[];for(let i=6;i>=0;i--){const d=ago(i);labels.push(new Date(d+'T00:00').toLocaleDateString('en-IN',{weekday:'short'}));v.push(S.exps.filter(e=>e.date===d).reduce((s,e)=>s+Number(e.amount||0),0))}destroy('spendingLine');S.charts.spendingLine=new Chart($('spendingLine'),{type:'line',data:{labels,datasets:[{data:v,borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.09)',fill:true,tension:.35,pointRadius:3,pointBackgroundColor:'#2563eb'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:10},color:'#94a3b8'}},y:{beginAtZero:true,grid:{color:'rgba(148,163,184,.12)'},ticks:{font:{size:10},color:'#94a3b8',callback:x=>'₹'+x}}}}})}
function activities(){const q=($('activitySearch').value||'').toLowerCase(),c=$('activityFilter').value,r=S.acts.filter(a=>(!c||a.category===c)&&(!q||`${a.name} ${a.category} ${a.notes||''}`.toLowerCase().includes(q))).sort(newest);$('activityCount').textContent=`${r.length} entr${r.length===1?'y':'ies'}`;$('activityList').innerHTML=r.length?r.map(actHTML).join(''):empty('No matching activities.')}
function expenses(){const q=($('expenseSearch').value||'').toLowerCase(),c=$('expenseFilter').value,r=S.exps.filter(e=>(!c||e.category===c)&&(!q||`${e.name} ${e.category} ${e.mode||''} ${e.notes||''}`.toLowerCase().includes(q))).sort(newest);$('expenseCount').textContent=`${r.length} entr${r.length===1?'y':'ies'}`;$('expenseList').innerHTML=r.length?r.map(expHTML).join(''):empty('No matching expenses.')}
function analytics(){const p=S.analytics,A=S.acts.filter(a=>inRange(a.date||'',p)),E=S.exps.filter(e=>inRange(e.date||'',p)),ac={},ec={},pm={};A.forEach(a=>ac[a.category]=(ac[a.category]||0)+Number(a.duration||0));E.forEach(e=>{ec[e.category]=(ec[e.category]||0)+Number(e.amount||0);pm[e.mode||'Other']=(pm[e.mode||'Other']||0)+Number(e.amount||0)});const ta=Object.entries(ac).sort((a,b)=>b[1]-a[1])[0],te=Object.entries(ec).sort((a,b)=>b[1]-a[1])[0],days=new Set(E.map(e=>e.date)).size,total=E.reduce((s,e)=>s+Number(e.amount||0),0);$('topActivity').textContent=ta?ta[0]:'—';$('topActivityMeta').textContent=ta?ta[1].toFixed(1)+'h logged':'No data';$('topExpense').textContent=te?te[0]:'—';$('topExpenseMeta').textContent=te?money(te[1]):'No data';$('avgSpend').textContent=money(days?total/days:0);$('avgSpendMeta').textContent=days?`${days} spending days`:'No spending data';const ar=Object.entries(ac).sort((a,b)=>b[1]-a[1]);destroy('activityBar');S.charts.activityBar=new Chart($('activityBar'),{type:'bar',data:{labels:ar.map(x=>x[0]),datasets:[{data:ar.map(x=>x[1]),backgroundColor:ar.map(x=>COLORS[x[0]]||COLORS.Other),borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:true}}}});const mr=Object.entries(pm);destroy('paymentPie');$('paymentLegend').innerHTML=mr.map(([c,v])=>`<span class="legend-item"><i class="legend-dot" style="background:${COLORS[c]||'#64748b'}"></i>${esc(c)} ${money(v)}</span>`).join('');if(mr.length)S.charts.paymentPie=new Chart($('paymentPie'),{type:'pie',data:{labels:mr.map(x=>x[0]),datasets:[{data:mr.map(x=>x[1]),backgroundColor:['#2563eb','#059669','#ea580c','#7c3aed','#64748b'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});const max=te?te[1]:1;$('categoryBars').innerHTML=Object.entries(ec).sort((a,b)=>b[1]-a[1]).map(([c,v])=>`<div class="category-row"><span>${esc(c)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,v/max*100)}%;background:${COLORS[c]||COLORS.Other}"></div></div><b>${money(v)}</b></div>`).join('')||empty('No expense data for this period.')}
function history(){const q=($('historySearch').value||'').toLowerCase(),t=$('historyType').value,r=all().filter(e=>(t==='all'||e.type===t)&&(!q||`${e.name} ${e.category} ${e.notes||''} ${e.mode||''}`.toLowerCase().includes(q)));$('historyList').innerHTML=r.length?r.map(e=>`<div class="timeline-entry ${e.type}"><div class="timeline-date">${shortDate(e.date)}<br>${esc(e.time||'')}</div><i class="timeline-line"></i><div><div class="timeline-title">${esc(e.name)}</div><div class="timeline-meta">${esc(e.category)}${e.type==='activity'?' · '+esc(e.status||'')+' · '+Number(e.duration||0).toFixed(2).replace(/\.00$/,'')+'h':' · '+esc(e.mode||'')}</div></div><div class="timeline-amount">${e.type==='expense'?money(e.amount):''}</div></div>`).join(''):empty('No history matches your search.')}
function render(){if(!S.loaded)return;dashboard();activities();expenses();analytics();history()}
function navigate(v){S.view=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const m={dashboard:['OVERVIEW','Good day 👋'],activities:['TRACK','Activities'],expenses:['MONEY','Expenses'],analytics:['INSIGHTS','Analytics'],history:['TIMELINE','History'],settings:['CONTROL CENTER','Settings']};$('viewKicker').textContent=m[v][0];$('viewTitle').textContent=m[v][1];$('sidebar').classList.remove('open');$('sidebarOverlay').classList.remove('open');if(v==='analytics')setTimeout(analytics,30)}
function edit(type,id){const x=type==='activity'?S.acts.find(a=>a.id===id):S.exps.find(e=>e.id===id);if(!x)return;S.edit={type,id};const cats=type==='activity'?ACT_CATS:EXP_CATS;$('modalKicker').textContent='EDIT '+type.toUpperCase();$('modalTitle').textContent=type==='activity'?'Edit activity':'Edit expense';$('editForm').innerHTML=type==='activity'?`<label>Name<input id="mName" required value="${esc(x.name)}"></label><label>Category<select id="mCategory">${cats.map(c=>`<option ${c===x.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><div class="form-row"><label>Date<input id="mDate" type="date" required value="${esc(x.date||today())}"></label><label>Time<input id="mTime" type="time" value="${esc(x.time||'')}"></label></div><div class="form-row"><label>Duration<input id="mDuration" type="number" min="0" step="0.25" value="${Number(x.duration||0)}"></label><label>Status<select id="mStatus">${['Completed','Pending','In Progress','Cancelled'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></label></div><label>Notes<textarea id="mNotes" rows="3">${esc(x.notes||'')}</textarea><div class="form-actions"><button type="button" class="secondary-btn" id="modalCancel">Cancel</button><button class="primary-btn" type="submit">Save changes</button></div>`:`<label>Name<input id="mName" required value="${esc(x.name)}"></label><label>Category<select id="mCategory">${cats.map(c=>`<option ${c===x.category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><div class="form-row"><label>Amount (₹)<input id="mAmount" type="number" min="0.01" step="0.01" required value="${Number(x.amount||0)}"></label><label>Payment mode<select id="mMode">${['UPI','Cash','Card','Net Banking','Other'].map(s=>`<option ${s===x.mode?'selected':''}>${s}</option>`).join('')}</select></label></div><label>Date<input id="mDate" type="date" required value="${esc(x.date||today())}"></label><label>Notes<textarea id="mNotes" rows="3">${esc(x.notes||'')}</textarea><div class="form-actions"><button type="button" class="secondary-btn" id="modalCancel">Cancel</button><button class="primary-btn" type="submit">Save changes</button></div>`;$('modalBackdrop').classList.add('open');$('modalCancel').onclick=closeModal}
function closeModal(){$('modalBackdrop').classList.remove('open');S.edit=null}
async function del(type,id){if(!confirm(`Delete this ${type}? This cannot be undone.`))return;try{await deleteDoc(doc(db,type==='activity'?'activities':'expenses',id));toast('Deleted successfully')}catch(e){console.error(e);toast('Delete failed')}}
function download(name,text,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove()}
function csv(rows,heads){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;return[heads.map(q).join(','),...rows.map(r=>heads.map(h=>q(r[h])).join(','))].join('\n')}
function exportActs(){download(`daily-tracker-activities-${today()}.csv`,csv(S.acts,['date','time','name','category','duration','status','notes']));toast('Activities exported')}
function exportExps(){download(`daily-tracker-expenses-${today()}.csv`,csv(S.exps,['date','name','category','amount','mode','notes']));toast('Expenses exported')}
function backup(){download(`daily-tracker-backup-${today()}.json`,JSON.stringify({exportedAt:new Date().toISOString(),activities:S.acts,expenses:S.exps},null,2),'application/json');toast('Backup exported')}
async function clearData(){if(!S.acts.length&&!S.exps.length)return toast('There is no data to delete');if(!confirm('Delete ALL activities and expenses? This cannot be undone. Export a backup first if needed.'))return;try{await Promise.all([...S.acts.map(x=>deleteDoc(doc(db,'activities',x.id))),...S.exps.map(x=>deleteDoc(doc(db,'expenses',x.id)))]);toast('All tracker data deleted')}catch(e){console.error(e);toast('Some data could not be deleted')}}
async function saveAct(e){e.preventDefault();const name=$('aName').value.trim();if(!name)return;try{await addDoc(collection(db,'activities'),{name,category:$('aCategory').value,date:$('aDate').value||today(),time:$('aTime').value||now(),duration:Number($('aDuration').value||0),status:$('aStatus').value,notes:$('aNotes').value.trim()});e.target.reset();$('aCategory').value='Work';$('aDate').value=today();$('aTime').value=now();chips('activityCats','aCategory',ACT_CATS);toast('Activity saved ✓')}catch(err){console.error(err);toast('Could not save activity')}}
async function saveExp(e){e.preventDefault();const name=$('eName').value.trim(),amount=Number($('eAmount').value);if(!name||amount<=0)return toast('Enter a valid name and amount');try{await addDoc(collection(db,'expenses'),{name,category:$('eCategory').value,date:$('eDate').value||today(),amount,mode:$('eMode').value,notes:$('eNotes').value.trim()});e.target.reset();$('eCategory').value='Food';$('eDate').value=today();chips('expenseCats','eCategory',EXP_CATS);toast('Expense saved ✓')}catch(err){console.error(err);toast('Could not save expense')}}
async function saveEdit(e){e.preventDefault();if(!S.edit)return;const d=S.edit.type==='activity'?{name:$('mName').value.trim(),category:$('mCategory').value,date:$('mDate').value,time:$('mTime').value,duration:Number($('mDuration').value||0),status:$('mStatus').value,notes:$('mNotes').value.trim()}:{name:$('mName').value.trim(),category:$('mCategory').value,amount:Number($('mAmount').value),mode:$('mMode').value,date:$('mDate').value,notes:$('mNotes').value.trim()};try{await updateDoc(doc(db,S.edit.type==='activity'?'activities':'expenses',S.edit.id),d);closeModal();toast('Changes saved ✓')}catch(err){console.error(err);toast('Could not save changes')}}
function theme(){const d=localStorage.getItem('mdt_theme')==='dark';document.body.classList.toggle('dark',d);$('darkSwitch').classList.toggle('on',d)}function toggleTheme(){const d=!document.body.classList.contains('dark');document.body.classList.toggle('dark',d);$('darkSwitch').classList.toggle('on',d);localStorage.setItem('mdt_theme',d?'dark':'light')}
function newEntry(type){navigate(type==='activity'?'activities':'expenses');setTimeout(()=>$(type==='activity'?'aName':'eName').focus(),80)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));document.querySelectorAll('[data-open-modal]').forEach(b=>b.onclick=()=>newEntry(b.dataset.openModal));$('mobileMenu').onclick=()=>{$('sidebar').classList.add('open');$('sidebarOverlay').classList.add('open')};$('sidebarOverlay').onclick=()=>{$('sidebar').classList.remove('open');$('sidebarOverlay').classList.remove('open')};$('quickAddBtn').onclick=()=>newEntry('activity');document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.closest('.period-tabs').id==='dashPeriod'){S.dash=b.dataset.period;dashboard()}else{S.analytics=b.dataset.period;analytics()}});$('activityForm').onsubmit=saveAct;$('expenseForm').onsubmit=saveExp;$('editForm').onsubmit=saveEdit;$('modalClose').onclick=closeModal;$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))closeModal()};$('themeBtn').onclick=toggleTheme;$('darkSwitch').onclick=toggleTheme;$('activitySearch').oninput=activities;$('activityFilter').onchange=activities;$('expenseSearch').oninput=expenses;$('expenseFilter').onchange=expenses;$('historySearch').oninput=history;$('historyType').onchange=history;$('exportActivities').onclick=exportActs;$('exportExpenses').onclick=exportExps;$('exportBackup').onclick=backup;$('clearData').onclick=clearData;document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]'),de=e.target.closest('[data-delete]');if(ed){const[a,b]=ed.dataset.edit.split(':');edit(a,b)}if(de){const[a,b]=de.dataset.delete.split(':');del(a,b)}})}
function clock(){$('liveTime').textContent=new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true})}
function load(){if(!window.db||!window.onSnapshot)return toast('Firebase is not ready');onSnapshot(collection(db,'activities'),s=>{S.acts=s.docs.map(d=>({id:d.id,...d.data()}));S.loaded=true;render()},e=>{console.error(e);toast('Unable to load activities')});onSnapshot(collection(db,'expenses'),s=>{S.exps=s.docs.map(d=>({id:d.id,...d.data()}));S.loaded=true;render()},e=>{console.error(e);toast('Unable to load expenses')})}
function init(){bind();theme();$('activityFilter').innerHTML='<option value="">All categories</option>'+ACT_CATS.map(c=>`<option>${esc(c)}</option>`).join('');$('expenseFilter').innerHTML='<option value="">All categories</option>'+EXP_CATS.map(c=>`<option>${esc(c)}</option>`).join('');$('aDate').value=today();$('eDate').value=today();$('aTime').value=now();chips('activityCats','aCategory',ACT_CATS);chips('expenseCats','eCategory',EXP_CATS);clock();setInterval(clock,1000);load()}
addEventListener('DOMContentLoaded',init);